version: 2.1

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Explore
          command: |
            pwd
            cd ../.. && ls
            cd / && ls

workflows:
  main:
    jobs:
      - echo
